apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tellery.fullname" . }}-db-migrate
  labels:
    app: {{ include "tellery.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "2"
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-server.yaml") . | sha256sum }}
        {{- if .Values.server.annotations }}
{{ toYaml .Values.server.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ include "tellery.fullname" . }}
        release: {{ .Release.Name }}
        role: migration
        {{- if .Values.server.podLabels }}
{{ toYaml .Values.server.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.server.affinity }}
{{ toYaml .Values.server.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations:
{{ toYaml .Values.server.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.server.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.server.imagePullSecrets | indent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-migration
        image: {{ include "server.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.server.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - npm run typeorm migration:run
        env:
        - name: NODE_ENV
          value: production
        {{- if .Values.server.env }}
{{ toYaml .Values.server.env | indent 12 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "tellery.fullname" . }}-server
