{{- if and .Values.init.user.create -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tellery.fullname" . }}-user-create
  labels:
    app: {{ include "tellery.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "3"
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-server.yaml") . | sha256sum }}
        {{- if .Values.server.annotations }}
{{ toYaml .Values.server.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ include "tellery.fullname" . }}
        release: {{ .Release.Name }}
        role: migration
        {{- if .Values.server.podLabels }}
{{ toYaml .Values.server.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.server.affinity }}
{{ toYaml .Values.server.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.server.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations:
{{ toYaml .Values.server.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.server.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.server.imagePullSecrets | indent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-user-create
        image: {{ include "server.image" . }}
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.server.pullPolicy }}
        command:
        - /bin/sh
        - -c
        - npm run create:user
        env:
        - name: NODE_ENV
          value: production
        - name: CREATE_USER_EMAIL
          value: {{ .Values.init.user.email }}
        - name: CREATE_USER_NAME
          value: {{ .Values.init.user.name }}
        - name: CREATE_USER_PASSWORD
          value: {{ .Values.init.user.password }}
        {{- if .Values.server.env }}
{{ toYaml .Values.server.env | indent 12 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "tellery.fullname" . }}-server
{{- end -}}
