{{- $redisHost := include "tellery.redis.host" . -}}
{{- $redisPort := include "tellery.redis.port" . -}}
{{- $redisPass := include "tellery.redis.password" . -}}
{{- $pgHost := include "tellery.postgresql.host" . -}}
{{- $pgPort := include "tellery.postgresql.port" . -}}
{{- $pgUser := include "tellery.postgresql.username" . -}}
{{- $pgPass := include "tellery.postgresql.password" . -}}
{{- $pgDb := include "tellery.postgresql.database" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tellery.fullname" . }}-server
data:
  PG_HOST: {{ $pgHost }}
  PG_USERNAME: {{ $pgUser }}
  PG_PORT: {{ $pgPort | quote }}
  PG_DATABASE: {{ $pgDb }}
  PG_PASSWORD: {{ $pgPass }}
  {{- if .Values.system.search.language }}
  PG_SEARCH_LANGUAGE: {{ .Values.system.search.language }}
  {{- end }}
  {{- if .Values.system.search.plugin }}
  PG_SEARCH_PLUGIN: {{ .Values.system.search.plugin }}
  {{- end }}
  {{- if include "tellery.redis.enabled" . }}
  {{- if not $redisPass }}
  REDIS_URL: redis://:{{ $redisPass }}@{{ $redisHost }}:{{ $redisPort }}/0
  {{- else }}
  REDIS_URL: redis://{{ $redisHost }}:{{ $redisPort }}/0
  {{- end }}
  {{- end }}
  OBJECT_STORAGE_TYPE: {{ .Values.objectStorage.type }}
  {{- if .Values.objectStorage.endpoint }}
  OBJECT_STORAGE_ENDPOINT: {{ .Values.objectStorage.endpoint }}
  {{- end }}
  OBJECT_STORAGE_BUCKET: {{ .Values.objectStorage.bucket }}
  OBJECT_STORAGE_ACCESS_KEY_ID: {{ .Values.objectStorage.accessKey | quote }}
  OBJECT_STORAGE_ACCESS_KEY_SECRET: {{ .Values.objectStorage.secretKey | quote }}
  {{- if .Values.objectStorage.region }}
  OBJECT_STORAGE_REGION: {{ .Values.objectStorage.region }}
  {{- end}}
  OBJECT_STORAGE_CALLBACK_HOST: {{ .Values.system.web.protocol }}://{{ .Values.system.web.host }}
  EMAIL_USE_TLS: {{ .Values.email.tls | quote }}
  EMAIL_USERNAME: {{ .Values.email.username | quote }}
  EMAIL_PASSWORD: {{ .Values.email.password | quote }}
  EMAIL_PORT: {{ .Values.email.port | quote }}
  EMAIL_HOST: {{ default .Values.email.host .Values.ingress.hostname | quote }}
  EMAIL_FROM: {{ .Values.email.from | quote }}
  SECRET_KEY: {{ .Values.system.secretKey }}
  SERVER_PROTO: {{ .Values.system.web.protocol }}
  SERVER_HOST: {{ .Values.system.web.host }}
  SERVER_WEB_PORT: {{ .Values.system.web.port | quote }}
