{{- if .Values.connector.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tellery.fullname" . }}-connector
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tellery.fullname" . }}-connector
  minReplicas: {{ .Values.connector.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.connector.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.connector.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
