package io.tellery.connectors.profiles

import annotations.Dbt
import com.fasterxml.jackson.annotation.JsonInclude
import io.tellery.annotations.Config
import io.tellery.entities.Profile

@JsonInclude(JsonInclude.Include.NON_NULL)
@Dbt(
    type = "Snowflake",
    configs = [
        Config(
            name = "Git Url",
            type = Config.ConfigType.STRING,
            description = "The git url of your dbt repository. The format should be: git://[endpoint]:[organization_name]/[repo_name].git.",
            hint = "",
            required = false
        ),
        Config(
            name = "Dbt Project Name",
            type = Config.ConfigType.STRING,
            description = "The name of your dbt project, it should be equal with the name in dbt_project.yml.",
            hint = "",
            required = false
        ),
        Config(
            name = "Public Key",
            type = Config.ConfigType.STRING,
            description = "The public key generated by tellery for dbt repository, please copy it to the 'deploy key' in git server.",
            hint = "",
            required = false
        )
    ]
)
class SnowflakeDbtProfile(profile: Profile) : BaseDbtProfile(profile) {

    val account: String
    val user: String
    val password: String

    init {
        this.type = "snowflake"
        val account = getValueOrThrowException(profile, "Account Name")
        val region = getValueOrThrowException(profile, "Region Id")
        this.account = "$account.$region"
        this.user = getValueOrThrowException(profile, "Username")
        this.password = getValueOrThrowException(profile, "Password")
    }
}