module.exports = {
  postgres: {
    host: process.env.PG_HOST || '127.0.0.1',
    port: process.env.PG_PORT || 5432,
    username: process.env.PG_USERNAME || 'postgres',
    password: process.env.PG_PASSWORD || 'root',
    database: process.env.PG_DATABASE || 'tellery',
    searchLanguage: process.env.PG_SEARCH_LANGUAGE || 'en',
    searchPlugin: process.env.PG_SEARCH_PLUGIN,
  },
  redis: {
    url: process.env.REDIS_URL,
  },
  socket: {
    url: process.env.SOCKET_URL,
  },
  objectStorage: {
    type: process.env.OBJECT_STORAGE_TYPE || 'postgres',
    endpoint: process.env.OBJECT_STORAGE_ENDPOINT,
    bucket: process.env.OBJECT_STORAGE_BUCKET,
    accessKey: process.env.OBJECT_STORAGE_ACCESS_KEY_ID,
    secretKey: process.env.OBJECT_STORAGE_ACCESS_KEY_SECRET,
    region: process.env.OBJECT_STORAGE_REGION,
    cdn: process.env.OBJECT_STORAGE_CDN_ENDPOINT,
  },
  email: {
    backend: 'smtp',
    tls: process.env.EMAIL_USE_TLS || false,
    username: process.env.EMAIL_USERNAME,
    password: process.env.EMAIL_PASSWORD,
    port: process.env.EMAIL_PORT || 587,
    host: process.env.EMAIL_HOST,
    from: process.env.EMAIL_FROM,
  },
  secretKey: process.env.SECRET_KEY || 'SABD7KacL28vxZd6BgOSGStJGbh',
  server: {
    host: process.env.SERVER_HOST,
    protocol: process.env.SERVER_PROTO || 'http',
    webPort: parseInt(process.env.SERVER_WEB_PORT, 10) || 80,
    port: process.env.SERVER_PORT || 8000,
    keepAliveTimeout: process.env.SERVER_KEEP_ALIVE_TIMEOUT || 60 * 1000,
  },
  oauth2: {
    clientId: process.env.OAUTH2_CLIENT_ID ?? '',
    clientSecret: process.env.OAUTH2_CLIENT_SECRET ?? '',
    tokenUrl: process.env.OAUTH2_TOKEN_URL ?? '',
    userUrl: process.env.OAUTH2_USER_URL ?? '',
    userMethod: process.env.OAUTH2_USER_METHOD || 'GET',
    scope: process.env.OAUTH2_SCOPE || '*',
    grantType: process.env.OAUTH2_GRANT_TYPE || 'authorization_code',
    redirectUrl: process.env.OAUTH2_REDIRECT_URL ?? '',
    defaultWorkspaceId: process.env.OAUTH2_DEFAULT_WORKSPACE_ID ?? '',
  },
  // for SaaS usage
  deploy: {
    mode: process.env.DEPLOY_MODE || 'local',
    userServiceEndpoint: process.env.USER_SERVICE_ENDPOINT || '',
  },
  frontendConfig: {
    host: process.env.FRONTEND_HOST || '',
    assetsUrl: process.env.FRONTEND_ASSETS_URL || '../assets',
    sentry_dsn: process.env.FRONTEND_SENTRY_DSN || '',
    ga4Id: process.env.FRONTEND_GA4_ID || '',
    version: '0.8.6',
    asayerioProjectId: process.env.FRONTEND_ASAYERIO_PROJECT_ID || '',
    oauth2: {
      enable: process.env.OAUTH2_ENABLE || false,
      clientId: process.env.OAUTH2_CLIENT_ID || '',
      scope: process.env.OAUTH2_SCOPE || '*',
      providerName: process.env.OAUTH2_PROVIDER_NAME || 'provider',
      providerIcon: process.env.OAUTH2_PROVIDER_ICON || '',
      authorizeUrl: process.env.OAUTH2_AUTHORIZE_URL || '',
    },
  },
}
