const fsWalk = require('@nodelib/fs.walk')
const fs = require('fs')
const _ = require('lodash')

const output = 'src/assets/icons/index.ts'

function rename(path) {
  return _.upperFirst(_.camelCase(path.replace(/^src\/assets\/icons\//, '').replace(/\.svg$/, '')))
}

// eslint-disable-next-line node/handle-callback-err
fsWalk.walk('src/assets/icons', (error, entries) => {
  if (error) {
    console.error(error)
    return
  }
  fs.writeFileSync(output, '/** This file is generated by svg.js. DO NOT MODIFY **/\n')
  for (const entry of entries.sort((a, b) => a.path.localeCompare(b.path))) {
    if (entry.dirent.isFile() && entry.name.endsWith('.svg')) {
      fs.appendFileSync(
        output,
        `import Icon${rename(entry.path)} from './${entry.path.replace(/^src\/assets\/icons\//, '')}?component'\n`
      )
    }
  }
  fs.appendFileSync(output, '\nexport {\n')
  for (const entry of entries.sort((a, b) => a.path.localeCompare(b.path))) {
    if (entry.dirent.isFile() && entry.name.endsWith('.svg')) {
      fs.appendFileSync(output, `  Icon${rename(entry.path)},\n`)
    }
  }
  fs.appendFileSync(output, '}\n')
})
