name: docker-web

on:
  push:
    branches:
      - main
    paths:
      - "packages/web/**"
      - ".github/workflows/docker-web.yml"
  pull_request:
    branches:
      - main
    paths:
      - "packages/web/**"
      - ".github/workflows/docker-web.yml"

jobs:
  build-docker-image-and-push:
    defaults:
      run:
        working-directory: packages/web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Wrap Cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Static Files
        run: yarn build
        env:
          NODE_ENV: production

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to Registry
        uses: docker/build-push-action@v2
        with:
          context: ./packages/web
          file: ./packages/web/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-web:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}-web:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
