name: docker-connector

on:
  push:
    branches:
      - main
    paths:
      - "packages/connector/**"
      - ".github/workflows/docker-connector.yml"

jobs:
  build-and-publish:
    defaults:
      run:
        working-directory: packages/connector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2.3.1
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Publish to Docker Hub with Gradle
        run: ./gradlew build jib --image=docker.io/${{ github.repository_owner }}/connector:nightly

      - name: Build and Publish to Github Container Registry with Gradle
        run: ./gradlew build jib --image=ghcr.io/${{ github.repository_owner }}/connector:nightly
