# This is a basic workflow to help you get started with Actions

name: test-api

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
    paths: ["packages/api/**", ".github/workflows/test-api.yml"]
  pull_request:
    branches: [main]
    paths: ["packages/api/**", ".github/workflows/test-api.yml"]

defaults:
  run:
    working-directory: packages/api

jobs:
  unit-integration-testing-pg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: domechn/postgresql-action@master
        with:
          postgresql version: "10.2"
          postgresql db: tellery
          postgresql user: postgres
          postgresql password: root

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Npm Compile And Test
        env:
          NODE_ENV: test
        run: |
          npm ci
          npm run compile
          npm run typeorm schema:sync
          npm run typeorm migration:run
          npm run test

  unit-integration-testing-with-redis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: domechn/postgresql-action@master
        with:
          postgresql version: "10.2"
          postgresql db: tellery
          postgresql user: postgres
          postgresql password: root

      - name: Start Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: "5"
          number of databases: 100

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Npm Compile And Test
        env:
          NODE_ENV: test
        run: |
          npm ci
          npm run compile
          npm run typeorm schema:sync
          npm run typeorm migration:run
          REDIS_URL="redis://127.0.0.1:6379" npm run test
